INSERT INTO TB_PRICES_REGION (ID, REGION, PRICE) VALUES (1, 'NORTE', 20.83);
INSERT INTO TB_PRICES_REGION (ID, REGION, PRICE) VALUES (2, 'NORDESTE', 15.98);
INSERT INTO TB_PRICES_REGION (ID, REGION, PRICE) VALUES (3, 'SUL', 17.30);
INSERT INTO TB_PRICES_REGION (ID, REGION, PRICE) VALUES (4, 'SUDESTE', 7.85);
INSERT INTO TB_PRICES_REGION (ID, REGION, PRICE) VALUES (5, 'CENTRO-OESTE', 12.50);
